apiVersion: monitoring.rhobs/v1alpha1
kind: ThanosQuerier
metadata:
  name: example
  namespace: project-c
  labels:
    app: example
spec:
  selector:
    matchLabels:
      app: example
  namespaceSelector:
    matchNames:
    - project-a
    - project-b
