---
apiVersion: monitoring.rhobs/v1alpha1
kind: ThanosQuerier
metadata:
  name: metrics-api
  namespace: project-d
  labels:
    app.kubernetes.io/name: metrics-api
    app.kubernetes.io/part-of: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: monitoring
  namespaceSelector:
    matchNames:
      - project-a
      - project-b
      - project-c
