name: tools-cache
description: Caches development tools
runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      id: tools-cache
      with:
        path: ./tmp/bin
        key: ${{ runner.os }}-tools-${{ hashFiles('.github/tools') }}

    - name: Install Dependencies
      if: steps.tools-cache.outputs.cache-hit != 'true'
      shell: bash
      run: make tools

    - name: Show versions of the installed tools
      shell: bash
      run: |
        ls ./tmp/bin
        make validate-tools

    - name: Add tmp/bin to PATH
      shell: bash
      run: |
        echo "tmp/bin" >> "$GITHUB_PATH"
