apiVersion: v1
kind: Secret
metadata:
  name: lokistack-s3
stringData:
  endpoint: http://minio.openshift-cluster-observability-operator.svc:9000
  bucketnames: loki
  access_key_id: minio
  access_key_secret: minio123
---
apiVersion: v1
kind: Secret
metadata:
  name: tempostack-s3
stringData:
  endpoint: http://minio.openshift-cluster-observability-operator.svc:9000
  bucket: tempo
  access_key_id: minio
  access_key_secret: minio123
