name: e2e-tests-olm
description: Runs E2E tests against the OLM bundle using unified setup
inputs:
  kind-version:
    description: "kind version"
    required: false
    default: 'v0.29.0'
  kind-image:
    description: "kind node image"
    required: false
    default: 'kindest/node:v1.33.1'

runs:
  using: composite
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        check-latest: true

    - name: Install required tools using unified setup
      uses: ./.github/tools-cache

    - name: Set up e2e environment
      shell: bash
      run: |
        # Use the unified setup script with CI-friendly options
        ./hack/setup-e2e-env.sh \
          --skip-host-check \
          --kind-version ${{ inputs.kind-version }} \
          --kind-image ${{ inputs.kind-image }}
        echo $KUBECONFIG
        echo "KUBECONFIG=$KUBECONFIG" >> "$GITHUB_ENV"

    - name: Run e2e script
      shell: bash
      run: ./test/run-e2e.sh --ci

    - name: Capture cluster state
      if: always()
      shell: bash
      run: |
        # Capture apiserver state
        echo $KUBECONFIG
        oc adm inspect node --dest-dir cluster-state || true
        oc adm inspect -A statefulset --dest-dir cluster-state || true
        oc adm inspect -A deployment --dest-dir cluster-state || true
        oc adm inspect -A ns --dest-dir cluster-state || true
        cp -r tmp/e2e cluster-state/ || true

    - name: Archive production artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cluster-state
        path: cluster-state
