apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-k8sattributes
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-k8sattributes
roleRef:
  kind: ClusterRole
  name: otel-collector-k8sattributes
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: cluster-collector-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traces-writer-application
rules:
  - apiGroups: [tempo.grafana.com]
    resources: [application]
    resourceNames: [traces]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traces-writer-application
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traces-writer-application
subjects:
  - kind: ServiceAccount
    name: cluster-collector-collector
