apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- monitoring.thanos.io_thanoscompacts.yaml
- monitoring.thanos.io_thanosqueries.yaml
- monitoring.thanos.io_thanosreceives.yaml
- monitoring.thanos.io_thanosrulers.yaml
- monitoring.thanos.io_thanosstores.yaml

commonAnnotations:
  observability.openshift.io/api-support: TechPreviewNoUpgrade
