apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability-operator
resources:
- namespace.yaml
- ../../crds/kubernetes
commonAnnotations:
  package-operator.run/phase: crds
