name: 'Publish to OLM'
description: 'Publishes the operator to OLM'
inputs:
  quay_login:
    description: "Quay login"
    required: true
  quay_token:
    description: "Quay token"
    required: true
  go-version:
    description: "go version"
    required: true
runs:
  using: composite
  steps:
  - uses: actions/checkout@v3
    with:
      fetch-depth: 0

  - name: Setup Go environment
    uses: actions/setup-go@v3
    with:
      go-version: ${{ inputs.go-version }}
      check-latest: true
      cache: true

  - name: Install tools
    uses: ./.github/tools-cache

  - name: Registry Login
    uses: docker/login-action@v2
    with:
      registry: quay.io
      username: ${{ inputs.quay_login }}
      password: ${{ inputs.quay_token }}

  - name: Git merge olm-catalog branch
    shell: bash
    run: |
      git config user.name rhobs-release-bot
      git config user.email release-bot@monitoring.rhobs.io

      # NOTE: uses strategy-option=ours as bundle created for a release using
      # make initiate-release conflicts with the previous bundle created for
      # development branch, so the version in main takes precedence over the
      # one in olm-catalog branch
      git merge -Xours origin/olm-catalog  -m "ci: merge olm-catalog branch"

  - name: Build Operator Image
    shell: bash
    run: make operator-image

  - name: Publish Operator
    shell: bash
    run: make operator-push

  - name: Build Bundle Image
    shell: bash
    run: make bundle-image

  - name: Publish Bundle
    shell: bash
    run: make bundle-push


  - name: Build Catalog Image
    shell: bash
    run: |
      make catalog-image

      # NOTE: add a commit only if the catalog can built sucessfully
      git add bundle/ olm/
      git commit -m "ci(bot): update catalog image"

  - name: Publish catalog image
    shell: bash
    run: |
      make catalog-push

      # update olm-catalog only if catalog could be successfully published
      git push origin HEAD:olm-catalog
