# Default configuration for deploying Korrel8r as a service in an OpenShift cluster.
# Store service URLs assume that stores are installed in their default locations.
stores:
  - domain: k8s
  - domain: alert
    metrics: https://{{ .Metric }}.{{ .MonitoringNs }}.svc:9091
    alertmanager: https://{{ .MetricAlert }}.{{ .MonitoringNs }}.svc:9094
    certificateAuthority: ./run/secrets/kubernetes.io/serviceaccount/service-ca.crt
  - domain: log
    lokiStack: https://{{ .Log }}.{{ .LoggingNs }}.svc:8080
    certificateAuthority: ./run/secrets/kubernetes.io/serviceaccount/service-ca.crt
  - domain: otellog
    lokiStack: https://{{ .Log }}.{{ .LoggingNs }}.svc:8080
    certificateAuthority: ./run/secrets/kubernetes.io/serviceaccount/service-ca.crt
  - domain: metric
    metric: https://{{ .Metric }}.{{ .MonitoringNs }}.svc:9091
    certificateAuthority: ./run/secrets/kubernetes.io/serviceaccount/service-ca.crt
  - domain: netflow
    lokiStack: https://{{ .Netflow }}.{{ .NetobservNs }}.svc:8080
    certificateAuthority: ./run/secrets/kubernetes.io/serviceaccount/service-ca.crt
  - domain: trace
    tempoStack: https://{{ .Trace }}.{{ .TracingNs }}.svc.cluster.local:8080/api/traces/v1/platform/tempo/api/search
    certificateAuthority: ./run/secrets/kubernetes.io/serviceaccount/service-ca.crt

include:
  - /etc/korrel8r/rules/all.yaml
