---
apiVersion: v1
kind: Service
metadata:
  name: thanos-querier-example-coo-thanos
  namespace: project-b
spec:
  ports:
  - name: proxy
    port: 8888
    protocol: TCP
    targetPort: oauth-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-querier-example-coo-thanos
  namespace: project-b
spec:
  template:
    spec:
      containers:
      - args:
        - -provider=openshift
        - -https-address=:8888
        - -http-address=
        - -email-domain=*
        - -upstream=http://localhost:10902
        - -tls-cert=/etc/tls/private/tls.crt
        - -tls-key=/etc/tls/private/tls.key
        - -cookie-secret-file=/etc/proxy/secrets/session_secret
        - -openshift-service-account=thanos-querier-example-coo-thanos
        - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - -openshift-sar={"resource":"pods","namespace":"project-b","verb":"get"}
        image: quay.io/openshift/origin-oauth-proxy:4.19
        imagePullPolicy: IfNotPresent
        name: oauth-proxy
        ports:
        - containerPort: 8888
          name: oauth-proxy
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /etc/tls/private
          name: secret-thanos-tls
        - mountPath: /etc/proxy/secrets
          name: secret-thanos-proxy
        - mountPath: /tmp
          name: oauth-proxy-tmp
      serviceAccount: thanos-querier-example-coo-thanos
      serviceAccountName: thanos-querier-example-coo-thanos
      volumes:
      - name: secret-thanos-tls
        secret:
          secretName: thanos-tls
      - name: secret-thanos-proxy
        secret:
          secretName: thanos-proxy
      - name: oauth-proxy-tmp
        emptyDir: {}
