---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-querier-example-coo-thanos
  namespace: project-c
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.thanos-querier: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"thanos-querier-authenticated"}}'
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-querier-example-coo-thanos
  namespace: project-c
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: "thanos-tls"
