apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - monitoring.rhobs_monitoringstacks.yaml
  - monitoring.rhobs_thanosqueriers.yaml
  - observability.openshift.io_uiplugins.yaml
  - observability.openshift.io_observabilityinstallers.yaml
