apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

transformers:
  - namespace-transformer.yaml

components:
  # Collectors
  - ../../components/collectors/tracing/operator
  - ../../components/collectors/tracing/resources
  - ../../components/collectors/logging/operator
  - ../../components/collectors/logging/resources
  - ../../components/collectors/network/operator
  - ../../components/collectors/network/resources
  # Stores
  - ../../components/stores/lokistack/operator
  - ../../components/stores/lokistack/resources
  - ../../components/stores/tempostack/operator
  - ../../components/stores/tempostack/resources
  # Console
  - ../../components/console/resources
  # Shared
  - ../../components/s3-storage/minio
  - ../../components/korrel8r/resources

patches:
  - path: patches/korrel8r-config.yaml
