name: e2e-tests
description: Runs E2E tests
inputs:
  go-version:
    description: "go version"
    required: false
    default: 1.16
  kind-version:
    description: "kind version"
    required: false
    default: 'v0.11.1'
  kind-image:
    description: "kind version"
    required: false
    default: 'kindest/node:v1.22.0'

runs-on:
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v2.1.4
      with:
        go-version: 1.16

    - name: Build images
      run: make operator-image
      shell: bash

    - name: Start KinD
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: ${{ inputs.kind-version }}
        image: ${{ inputs.kind-image }}
        wait: 300s

    - name: Wait for cluster to finish bootstraping
      shell: bash
      run: |
        kubectl wait --for=condition=Ready pods --all --all-namespaces --timeout=300s
        kubectl cluster-info
        kubectl get pods -A

    - name: Load images
      shell: bash
      run: |
        kind load docker-image monitoring-stack-operator:$(cat VERSION)

    - name: Deploy the operator
      shell: bash
      run: |
        kubectl apply -k deploy/crds
        cd deploy/operator
        kustomize edit set namespace operators
        kubectl create ns operators
        kubectl apply -k .

    - name: Wait for CRDs to become ready
      shell: bash
      run: |
        kubectl wait --for=condition=Established crds --all --timeout=300s

    - name: Run tests
      shell: bash
      run: go test ./test/e2e/... --with-operator=false
