name: 'Publish OSD test harness image'
description: 'Publishes the OSD test harness image'
inputs:
  quay_login:
    description: "Quay login"
    required: true
  quay_token:
    description: "Quay token"
    required: true
runs:
  using: composite
  steps:
  - name: Setup Go environment
    uses: actions/setup-go@v5
    with:
      go-version-file: 'go.mod'
      check-latest: true

  - name: Install tools
    uses: ./.github/tools-cache

  - name: Registry Login
    uses: docker/login-action@v2
    with:
      registry: quay.io
      username: ${{ inputs.quay_login }}
      password: ${{ inputs.quay_token }}

  - name: Build and publish test harness image
    shell: bash
    run: |
      make osd-e2e-test-push
