{
 "title": "Cluster observability operator - Overview",
 "tags": [ "coo" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "version",
    "query": {
     "query": "label_values(csv_succeeded{name=~\"cluster-observability-operator.*\"},version)"
    }
   },
   {
    "name": "resource",
    "query": {
     "query": "label_values(cluster:usage:resources:sum{resource=~\".+monitoring.rhobs|uiplugins.observability.openshift.io|clusterobservabilities.observability.openshift.io\"},resource)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Clusters with COO installed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sort_desc(count by (version) (label_replace(csv_succeeded{name=~\"cluster-observability-operator.*\",version=~\"$version\"}, \"name\", \"$1\",\"name\", \"(cluster-observability-operator).*\")))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Installation failure rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "count by(version) (group by(_id,version) (csv_succeeded{name=~\"cluster-observability-operator.*\",version=~\"$version\"} == 0)) / count by(version) (group by(_id,version) (csv_succeeded{name=~\"cluster-observability-operator.*\",version=~\"$version\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Approval/channel break-down",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sort_desc(count by(approval,channel) (\ngroup by(_id,approval, channel) (topk by(_id, installed) (1, subscription_sync_total{name=\"cluster-observability-operator\", installed!=\"\"}))\n* on(_id,package) group_left() group by(_id, installed) (label_replace(csv_succeeded{name=~\"cluster-observability-operator.+\"} > 0, \"installed\", \"$1\", \"name\", \".+\"))))",
     "legendFormat": "approval={{approval}},channel={{channel}}"
    }
   ]
  },
  {
   "title": "Phase/reason failures",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sort_desc(count by(reason,phase) (topk by(name, version,reason,phase, _id) (1, csv_abnormal{name=~\"cluster-observability-operator.+\",version=~\"$version\"} == 1)))",
     "legendFormat": "phase={{phase}},reason={{reason}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "sort_desc(count by(alertname, severity) (alerts{namespace=\"openshift-observability-operator\"} * on (_id) group_left()\n    group by (_id) (csv_succeeded{name=~\"cluster-observability-operator.+\",version=~\"$version\"})))",
     "legendFormat": "{{alertname}} ({{severity}})"
    }
   ]
  },
  {
   "title": "Number of ${resource} instances",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count by (resource) (\n    (max by (resource, _id) (cluster:usage:resources:sum{resource=~\"${resource}\"}) > 0)\n  * on (_id) group_left ()\n    group by (_id) (csv_succeeded{name=~\"cluster-observability-operator.+\",version=~\"$version\"})\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}