apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding-system-auth-delegator.yaml
  - clusterrolebinding-perses.yaml
