apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: placeholder-uiplugin-name-korrel8r
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: korrel8r-view
subjects:
  - kind: ServiceAccount
    name: placeholder-uiplugin-name-sa
