apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - korrel8r-deployment.yaml
  - korrel8r-service.yaml
  - korrel8r-configmap.yaml
  - korrel8r-clusterrole.yaml
  - korrel8r-clusterrolebinding.yaml
