apiVersion: v1
kind: Service
metadata:
  name: health-analyzer
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: health-analyzer-tls
  labels:
    app.kubernetes.io/instance: health-analyzer
    app.kubernetes.io/managed-by: observability-operator
    app.kubernetes.io/part-of: UIPlugin
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: health-analyzer
  ports:
    - name: metrics
      port: 8443
      targetPort: metrics
