apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: health-analyzer
spec:
  endpoints:
    - interval: 30s
      port: metrics
      scheme: https
      tlsConfig:
        caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
        certFile: /etc/prometheus/secrets/metrics-client-certs/tls.crt
        keyFile: /etc/prometheus/secrets/metrics-client-certs/tls.key
        serverName: health-analyzer.NAMESPACE.svc
  selector:
    matchLabels:
      app.kubernetes.io/instance: health-analyzer
