name: 'Publish package-operator package'
description: 'Publishes the operator as a package-operator package'
inputs:
  quay_login:
    description: "Quay login"
    required: true
  quay_token:
    description: "Quay token"
    required: true
runs:
  using: composite
  steps:
  - name: Setup Go environment
    uses: actions/setup-go@v5
    with:
      go-version-file: 'go.mod'
      check-latest: true

  - name: Install tools
    uses: ./.github/tools-cache

  - name: Registry Login
    uses: docker/login-action@v2
    with:
      registry: quay.io
      username: ${{ inputs.quay_login }}
      password: ${{ inputs.quay_token }}

  - name: Generate Package image
    shell: bash
    run: make package

  - name: Publish Package
    shell: bash
    run: make package-push

  - name: Generate Package image with kubeconfig option
    shell: bash
    run: make package-kubeconfig

  - name: Publish Package with kubeconfig option
    shell: bash
    run: make package-push-kubeconfig
