apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-logging-audit-view
rules:
  - apiGroups:
      - loki.grafana.com
    resources:
      - audit
    resourceNames:
      - logs
    verbs:
      - get
