apiVersion: v1
kind: Service
metadata:
  name: logging
  labels:
    app.kubernetes.io/instance: logging
    app.kubernetes.io/managed-by: observability-operator
    app.kubernetes.io/part-of: UIPlugin
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: logging
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: logging
    app.kubernetes.io/managed-by: observability-operator
    app.kubernetes.io/part-of: UIPlugin
  ports:
    - name: http
      port: 9443
      protocol: TCP
      targetPort: 9443
